### ISSUE TITLE
Since version 0.6, not deploying in WAR

### ISSUE THREAD

**Issue by slibert** [johannest/border-layout#1]
Hello,

We are using your addon ( good job ! ) since version 0.4 without any issue.
Since 0.6, we are facing a strange issue : add-on is working in our development environment (Eclipse with Vaadin Plugin), but when we deploy to WAR file, borderlayout0.6.jar is missing.
We are using IVY for dependence management. It is still working great with older version of borderlayout, and it's not related to one projet (one Eclipse profile) as we have same behavior in all 3 projets in wich we use borderlayout add-on.

Any idea ? 

Regards

**Comment by johannest** [comment]
Thanks, I will see if I can reproduce the issue as soon as possible.

**Comment by johannest** [comment]
How do you create the war file? I tested Eclipse's war file export (Export->Web->WAR File) and at least it seemed to work all right: the BorderLayout-0.6.jar was in the WEB-INF/lib folder.

**Comment by slibert** [comment]
I'm using Eclipse with IVY and ANT
borderlayout is managed by ivy as a dependency, and ANT is creating the WAR.
If I go back to borderlayout 0.5 (changing ivy dependency), jar is again in
the generated WAR.
With borderlayout 0.6, it's not.

Could it be someting in pom configuration ?

2015-12-08 14:07 GMT+01:00 Johannes Tuikkala notifications@github.com:

**Comment by johannest** [comment]
I did some general clean up for it in version 0.6.. It's hard to say what
is failing without seeing your build script first.

**Comment by slibert** [comment]
Here is my ivy section (ivy.xml) :

<dependencies defaultconf="default" defaultconfmapping="default->default">

...

```
       <dependency org="org.vaadin.addons" name="borderlayout"
```

rev="0.6" />

Here is my ant section :

```
<ivy:cachepath pathid="ivy.deps.default" conf="default" />
<ivy:cachepath pathid="ivy.deps.widgetset" conf="widgetset-compile" />
<ivy:cachefileset setid="ivy.deps.default.fileset" conf="default" />

<target name="package-war" depends="-init" description="Packages
```

everything in a WAR that has been deployed in ${workdir}">
        <mkdir dir="${workdir}/WEB-INF/lib"/>
        <copy todir="${workdir}/WEB-INF/lib" flatten="true">
            <fileset refid="ivy.deps.default.fileset"/>
        </copy>

```
    <copy todir="${workdir}/WEB-INF/classes">
        <fileset dir="build">
            <include name="**/*.class"/>
            <include name="**/liquibase/*.xml"/>
            <include name="**/liquibase/instance/*.xml"/>
        </fileset>
    </copy>

    <copy todir="${workdir}/VAADIN/themes/">
        <fileset dir="${webroot}/VAADIN/themes/"/>
    </copy>

    <copy todir="${workdir}/VAADIN/widgetsets">
        <fileset dir="${webroot}/VAADIN/widgetsets"/>
    </copy>

    <copy todir="${workdir}/WEB-INF">
        <fileset dir="${webroot}/WEB-INF">
            <include name="applicationContext.xml"/>
        </fileset>
    </copy>



    <delete>
        <fileset dir="${workdir}/WEB-INF/lib">
            <include name="**/*-sources.jar"/>
            <include name="**/*-javadoc.jar"/>
        </fileset>
    </delete>

    <war destfile="${artifacts}/${warfilename}"
        basedir="${workdir}"
        webxml="${webroot}/WEB-INF/web.xml"
        >

        <lib dir="${webroot}/WEB-INF/lib" erroronmissingdir="no">
            <include name="*.jar"/>
        </lib>
        <lib dir="${libraries}" erroronmissingdir="no">
            <include name="*.jar"/>
        </lib>
    </war>
</target>
```

All other vaadin addons are copied onto the WAR file. BorderLayout0.6.jar
is the only one that does not.
I tries to create a new Eclipse profile, same behavior.
And it's happening on 3 multiples differents projets.

Regards
Sebastien

2015-12-08 14:23 GMT+01:00 Johannes Tuikkala notifications@github.com:

> I did some general clean up for it in version 0.6.. It's hard to say what
> is failing without seeing your build script first.
>

**Comment by johannest** [comment]
Strange.. Does the BorderLayout-0.6.jar appear in the directory ${workdir}/WEB-INF/lib ? How those ivy dependencies are copied into that ${workdir}/WEB-INF/lib, I cant see that part in your script? I assume you did try cleaning ivy caches, ivy refresh, resolve, and reload settings?

**Comment by slibert** [comment]
No, file is not in the workdir /lib, it's probably related with ivy that,
for some reason, does not copy it. This is why I was suspecting some defect
in pom.xml (or equivalent I'm not ivy-expert)
Copy is made in ANT with command :
        <copy todir="${workdir}/WEB-INF/lib" flatten="true">
            <fileset refid="ivy.deps.default.fileset"/>
        </copy>

Yes i did the refresh/clean/and so on stuff ;-)

2015-12-09 14:18 GMT+01:00 Johannes Tuikkala notifications@github.com:

**Comment by johannest** [comment]
I'm not ivy-expert either.. Found this with google, but I don't whether it helps:
http://stackoverflow.com/questions/6218454/ivy-not-installing-some-jars

**Comment by slibert** [comment]
Ok, I found it.
Since 0.6, dependency as changed. A really small detail ;-)

```
<dependency org="org.vaadin.addons" name="borderlayout" rev="0.5" />
<dependency org="org.vaadin.addons" name="BorderLayout" rev="0.6" />
```

After some resolve/refresh/clean, now it's working as nicely as before.
Many thanks for taking time to investigate.

Regards
Sebastien
